from utils import openrouter

def chat_with_deepseekr1(text: str):
    """
    Function to interact with DeepSeek: R1 model for text generation.
    
    Args:
        text (str): The input text to be processed by the model.
        
    Returns:
        str: The response generated by the model.
    """
    
    response = openrouter.client.chat.completions.create(
        model="deepseek/deepseek-r1:free",
        temperature=0.0,
        messages=[
            {
              "role": "system",
              "content": "No explain, just return the final answer in JSON format."
            },
            {
                "role": "user",
                "content": text
            }
        ]
    )
    
    return response.choices[0].message.content

