import os
from google import genai
from dotenv import load_dotenv

env_path = os.path.join(os.path.dirname(__file__), '.env')
# load the env file
load_dotenv(dotenv_path=env_path)
client = genai.Client(api_key=os.getenv("GEMINI_KEY"))

def chat_with_gemini2_5(text: str) -> str:
    """
    Function to interact with Gemini 2.5 model for text generation.
    
    Args:
        text (str): The input text to be processed by the model.
        
    Returns:
        str: The response generated by the model.
    """
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=text,
    )
    
    return response.text

if __name__ == "__main__":
    # Example usage
    example_text = "What is the capital of France?"
    response = chat_with_gemini2_5(example_text)
    print(f"Response from Gemini 2.5: {response}")
