import os
from openai import OpenAI
from dotenv import load_dotenv

env_path = os.path.join(os.path.dirname(__file__), '.env')
# load the env file
load_dotenv(dotenv_path=env_path)

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("OPEN_ROUTER_KEY"),
)

def chat_with_qwen2_5_72b(text: str) -> str:
    """
    Function to interact with Qwen 2.5 72B model for text generation.
    
    Args:
        text (str): The input text to be processed by the model.
        
    Returns:
        str: The response generated by the model.
    """
    response = client.chat.completions.create(
        model="qwen/qwen-2.5-72b-instruct:free",
        messages=[
            {
              "role": "system",
              "content": "You are a helpful assistant that always answer as JSON."
            },
            {
                "role": "user",
                "content": text
            }
        ]
    )
    
    return response.choices[0].message.content

if __name__ == "__main__":
  # Example usage
  example_text = "What is the capital of France?"
  response = chat_with_qwen2_5_72b(example_text)
  print(f"Response from Qwen 2.5: {response}")