from utils import typhoon

def chat_with_typhoon(text: str) -> str:
    """
    Function to interact with Typhoon model for text generation.
    
    Args:
        text (str): The input text to be processed by the model.
        
    Returns:
        str: The response generated by the model.
    """
    response = typhoon.client.chat.completions.create(
        model="typhoon-v2.1-12b-instruct",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant that always answers in JSON format."
            },
            {
                "role": "user",
                "content": text
            }
        ]
    )
    
    if not response:
        return "Return an empty string from the model."
    
    return response.choices[0].message.content

if __name__ == "__main__":
    # Example usage
    example_text = "What is the capital of France?"
    response = chat_with_typhoon(example_text)
    print(f"Response from Typhoon: {response}")